import { darkTheme, lightTheme } from '@config/theme';

export const Colors = {
  light: {
    text: lightTheme.colors.onBackground,
    background: lightTheme.colors.background,
    onBackground: lightTheme.colors.onBackground,
    primary: lightTheme.colors.primary,
    onPrimaryContainer: lightTheme.colors.onPrimaryContainer,
    secondary: lightTheme.colors.secondary,
    surface: lightTheme.colors.surface,
    onSurface: lightTheme.colors.onSurface,
    inverseSurface: lightTheme.colors.inverseSurface,
    onSurfaceVariant: lightTheme.colors.onSurfaceVariant,
    outline: lightTheme.colors.outline,
    icon: lightTheme.colors.inversePrimary,
    error: lightTheme.colors.error,
    onError: lightTheme.colors.onError,
  },
  dark: {
    text: darkTheme.colors.onBackground,
    background: darkTheme.colors.background,
    onBackground: darkTheme.colors.onBackground,
    primary: darkTheme.colors.primary,
    onPrimaryContainer: darkTheme.colors.onPrimaryContainer,
    secondary: darkTheme.colors.secondary,
    surface: darkTheme.colors.surface,
    inverseSurface: darkTheme.colors.inverseSurface,
    onSurface: darkTheme.colors.onSurface,
    onSurfaceVariant: darkTheme.colors.onSurfaceVariant,
    outline: darkTheme.colors.outline,
    icon: darkTheme.colors.inversePrimary,
    error: darkTheme.colors.error,
    onError: darkTheme.colors.onError,
  },
};
